### ISSUE TITLE
Look into Zbb Basic bit-manipulation specification

### ISSUE THREAD

**Issue by avrong** [avrong/v8-bitmanip#4]
- Research ZBb - Basic bit-manipulation extentions and their usage, classify them into groups, would be also good to prioritize them in terms of implemenation.
- Prepare a doc explaining how their implementation can optimize current cases using base risc-v intructions.
- Also, it would be good to look into code and find cases where bitmanip instructions can be applicable. OpenJDK might be a good example for their implementation.

[RISC-V Bitmanip specification doc](https://github.com/riscv/riscv-bitmanip/releases/download/1.0.0/bitmanip-1.0.0.pdf)

**Comment by artem-devtools** [comment]
https://github.com/avrong/v8-bitmanip/wiki/Instructions#zbb-basic-bit-manipulation
